In [126]:
import pandas as pd
import numpy as np

In [146]:
junctions = pd.DataFrame(np.random.randint(50,100,size=(1000, 4)), columns=['a','b','c','d'])

In [148]:
junctions_lanes_a = pd.DataFrame(np.random.randint(5,15,size=(1000, 8)), columns=['a_lane_input_1','a_lane_output_1','a_lane_input_2','a_lane_output_2','a_lane_input_3','a_lane_output_3','a_lane_input_4','a_lane_output_4'])

In [149]:
junctions_lanes_b = pd.DataFrame(np.random.randint(5,15,size=(1000, 8)), columns=['b_lane_input_1','b_lane_output_1','b_lane_input_2','b_lane_output_2','b_lane_input_3','b_lane_output_3','b_lane_input_4','b_lane_output_4'])

In [150]:
junctions_lanes_c = pd.DataFrame(np.random.randint(5,15,size=(1000, 8)), columns=['c_lane_input_1','c_lane_output_1','c_lane_input_2','c_lane_output_2','c_lane_input_3','c_lane_output_3','c_lane_input_4','c_lane_output_4'])

In [151]:
junctions_lanes_d = pd.DataFrame(np.random.randint(5,15,size=(1000, 10)), columns=['d_lane_input_1','d_lane_output_1','d_lane_input_2','d_lane_output_2','d_lane_input_3','d_lane_output_3','d_lane_input_4','d_lane_output_4','d_lane_input_5','d_lane_output_5'])

In [153]:
result = pd.concat([junctions, junctions_lanes_a,junctions_lanes_b,junctions_lanes_c,junctions_lanes_d], axis=1)

In [155]:
result.to_csv('traffic_dataset.csv')

,a,b,c,d,a_lane_input_1,a_lane_output_1,a_lane_input_2,a_lane_output_2,a_lane_input_3,a_lane_output_3,...,d_lane_input_1,d_lane_output_1,d_lane_input_2,d_lane_output_2,d_lane_input_3,d_lane_output_3,d_lane_input_4,d_lane_output_4,d_lane_input_5,d_lane_output_5
0,57,68,64,82,7,7,14,10,7,14,...,10,7,13,12,6,7,6,14,10,7
1,78,66,93,98,11,9,8,9,10,10,...,6,12,8,11,14,5,8,10,14,8
2,87,70,93,69,13,8,14,14,13,14,...,8,14,8,9,12,6,6,5,11,14
3,60,94,94,54,13,9,7,6,8,5,...,14,9,7,13,5,6,10,7,14,9
4,85,65,73,92,13,10,14,5,13,13,...,5,14,5,9,5,10,8,12,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,54,50,93,65,6,11,10,10,5,9,...,5,11,12,7,10,6,11,13,11,9
996,86,94,68,68,7,7,10,9,9,8,...,10,6,12,9,7,13,14,14,12,8
997,94,56,78,70,11,8,8,9,5,8,...,9,6,6,8,11,10,5,14,9,14
998,67,51,52,55,8,7,12,10,8,9,...,10,12,5,7,9,7,9,11,7,6
999,51,73,96,71,5,14,10,6,5,7,...,12,8,13,14,13,6,9,13,6,7

In [156]:
result.to_csv("traffic_dataset")